<?php


$config = [
    'project'       => 'SHOPCLONE6',
    'version'       => '3.0.1',
    'max_time_load' => 4
];

 
$config_listbank = [
    'Vietcombank',
    'ACB',
    'MBBank',
    'VPBank',
    'Techcombank',
    'TPBank',
    'VPBank',
    'Vietinbank',
    'Sacombank',
    'THESIEURE',
    'MOMO',
    'Viettelpay',
    'Zalo Pay',
    'Cake',
    'Shopee Pay',
    'MSB',
    'NamABank',
    'LienVietPostBank',
    'VietCapitalBank',
    'BIDV',
    'VIB',
    'HDBank',
    'SeABank',
    'GPBank',
    'PVcomBank',
    'NCB',
    'ShinhanBank',
    'SCB',
    'PGBank',
    'Agribank',
    'SaigonBank',
    'DongABank',
    'BacABank',
    'StandardChartered',
    'Oceanbank',
    'VRB',
    'ABBANK',
    'VietABank',
    'Eximbank',
    'VietBank',
    'IndovinaBank',
    'BaoVietBank',
    'PublicBank',
    'SHB',
    'CBBank',
    'OCB',
    'KienLongBank',
    'CIMB',
    'HSBC',
    'DBSBank',
    'Nonghyup',
    'HongLeong',
    'IBK Bank',
    'Woori',
    'UnitedOverseas',
    'KookminHN',
    'KookminHCM',
    'COOPBANK',
    'Kasikorn Bank',
    'Siam Commercial Bank',
    'Bank of Ayudthya',
    'Krungthai Bank',
    'Bangkok Bank',
    'Thanachart Bank'

];
