<?php


$config = [
    'project'       => 'SHOPCLONE6',
    'version'       => '7.4.1',
    'max_time_load' => 4,
    'limit_block_login_client'  => 10,
    'limit_block_ip_login_client'  => 5
];

$config_listbank_auto = [
    'Vietcombank'   => 'Ngân hàng TMCP Ngoại Thương Việt Nam Vietcombank',
    'MBBank'        => 'Ngân hàng TMCP Quân đội MBBank',
    'ACB'           => 'Ngân hàng TMCP Á Châu ACB',
    'Techcombank'   => 'Ngân hàng TMCP Kỹ thương Việt Nam Techcombank',
    'TPBank'        => 'Ngân hàng TMCP Tiên Phong TPBank',
    'VietinBank' => 'Ngân hàng TMCP Công thương Việt Nam VietinBank',
    'BIDV' => 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam BIDV'
];

$config_listbank = [
    'THESIEURE'      => 'Ví THESIEURE.COM',
    'MOMO'      => 'Ví điện tử MOMO',
    'Zalo Pay'      => 'Ví điện tử Zalo Pay',
    'VietinBank' => 'Ngân hàng TMCP Công thương Việt Nam VietinBank',
    'Vietcombank' => 'Ngân hàng TMCP Ngoại Thương Việt Nam Vietcombank',
    'BIDV' => 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam BIDV',
    'Agribank' => 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam Agribank',
    'OCB' => 'Ngân hàng TMCP Phương Đông OCB',
    'MBBank' => 'Ngân hàng TMCP Quân đội MBBank',
    'Techcombank' => 'Ngân hàng TMCP Kỹ thương Việt Nam Techcombank',
    'ACB' => 'Ngân hàng TMCP Á Châu ACB',
    'VPBank' => 'Ngân hàng TMCP Việt Nam Thịnh Vượng VPBank',
    'TPBank' => 'Ngân hàng TMCP Tiên Phong TPBank',
    'Sacombank' => 'Ngân hàng TMCP Sài Gòn Thương Tín Sacombank',
    'HDBank' => 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh HDBank',
    'VietCapitalBank' => 'Ngân hàng TMCP Bản Việt VietCapitalBank',
    'SCB' => 'Ngân hàng TMCP Sài Gòn SCB',
    'VIB' => 'Ngân hàng TMCP Quốc tế Việt Nam VIB',
    'SHB' => 'Ngân hàng TMCP Sài Gòn - Hà Nội SHB',
    'Eximbank' => 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam Eximbank',
    'MSB' => 'Ngân hàng TMCP Hàng Hải MSB',
    'CAKE' => 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank CAKE',
    'Ubank' => 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank Ubank',
    'SaigonBank' => 'Ngân hàng TMCP Sài Gòn Công Thương SaigonBank',
    'BacABank' => 'Ngân hàng TMCP Bắc Á BacABank',
    'PVcomBank' => 'Ngân hàng TMCP Đại Chúng Việt Nam PVcomBank',
    'Oceanbank' => 'Ngân hàng Thương mại TNHH MTV Đại Dương Oceanbank',
    'NCB' => 'Ngân hàng TMCP Quốc Dân NCB',
    'ShinhanBank' => 'Ngân hàng TNHH MTV Shinhan Việt Nam ShinhanBank',
    'ABBANK' => 'Ngân hàng TMCP An Bình ABBANK',
    'VietABank' => 'Ngân hàng TMCP Việt Á VietABank',
    'NamABank' => 'Ngân hàng TMCP Nam Á NamABank',
    'PGBank' => 'Ngân hàng TMCP Xăng dầu Petrolimex PGBank',
    'VietBank' => 'Ngân hàng TMCP Việt Nam Thương Tín VietBank',
    'BaoVietBank' => 'Ngân hàng TMCP Bảo Việt BaoVietBank',
    'SeABank' => 'Ngân hàng TMCP Đông Nam Á SeABank',
    'COOPBANK' => 'Ngân hàng Hợp tác xã Việt Nam COOPBANK',
    'LienVietPostBank' => 'Ngân hàng TMCP Bưu Điện Liên Việt LienVietPostBank',
    'KienLongBank' => 'Ngân hàng TMCP Kiên Long KienLongBank',
    'KBank' => 'Ngân hàng Đại chúng TNHH Kasikornbank KBank',
    'GPBank' => 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu GPBank',
    'CBBank' => 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam CBBank',
    'CIMB' => 'Ngân hàng TNHH MTV CIMB Việt Nam CIMB',
    'DBSBank' => 'DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh DBSBank',
    'DongABank' => 'Ngân hàng TMCP Đông Á DongABank',
    'KookminHCM' => 'Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh KookminHCM',
    'KookminHN' => 'Ngân hàng Kookmin - Chi nhánh Hà Nội KookminHN',
    'Woori' => 'Ngân hàng TNHH MTV Woori Việt Nam Woori',
    'VRB' => 'Ngân hàng Liên doanh Việt - Nga VRB',
    'StandardChartered' => 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam StandardChartered',
    'HongLeong' => 'Ngân hàng TNHH MTV Hong Leong Việt Nam HongLeong',
    'HSBC' => 'Ngân hàng TNHH MTV HSBC (Việt Nam) HSBC',
    'IBKHN' => 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội IBKHN',
    'IBKHCM' => 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh IBKHCM',
    'IndovinaBank' => 'Ngân hàng TNHH Indovina IndovinaBank',
    'Nonghyup' => 'Ngân hàng Nonghyup - Chi nhánh Hà Nội Nonghyup',
    'UnitedOverseas' => 'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh UnitedOverseas',
    'PublicBank' => 'Ngân hàng TNHH MTV Public Việt Nam PublicBank',
    'Kasikorn Bank' => 'Kasikorn Bank',
    'Siam Commercial Bank'  => 'Siam Commercial Bank',
    'Bank of Ayudthya'  => 'Bank of Ayudthya',
    'Krungthai Bank'    => 'Krungthai Bank',
    'Bangkok Bank'      => 'Bangkok Bank',
    'ICICI Bank'        => 'ICICI Bank',
    'HDFC Bank'         => 'HDFC Bank',
    'State Bank of India'   => 'State Bank of India',
    'ABA Bank'     => 'ABA Bank Cambodia',
    'Wing Bank' => 'Wing Bank',
    'Maybank'   => 'Maybank',
    'CIMB Clicks Malaysia' => 'CIMB Clicks Malaysia',
    'United Bank for Africa (UBA)'  => 'United Bank for Africa (UBA)',
    'Wise.com'  => 'Wise.com',
    'Binance'   => 'Binance',
    'Bitcoin'   => 'Bitcoin',
    'USDT'      => 'USDT',
    'Payoneer'  => 'Payoneer',
    'Algérie Poste' => 'Algérie Poste',
    'Paysera'       => 'Paysera',
    'Mercado Pago'  => 'Mercado Pago',
    'Banco Inter'   => 'Banco Inter'
    
];
 
$ip_server_black = [
  
];

$domain_black = [
    'trumbanclone.pw',
    'blog.sieuthicode.net',
    'sieuthidark.com',
    'xubymon36.com',
    'viatrau.me',
    'shopmailco.com',
    'clonebysun.net',
    'phongxu.com',
    'minhclone.com',
    'rdsieuvip.com',
    'sellviaxu.com',
    'autordff.com',
    'clonengoaiviet.com',
    'dichvuthanhtoan.site',
    'trumrandom.com',
    'mailcovip.com',
    'nguyenlieufacebook.com',
    'sieuthixu.pro',
    'khoichange.com',
    'maihuybao.live',
    'shopclonexu.com',
    'randomxin.com',
    'mailgiare.pro',
    'mailngon24h.online',
    'cloudnetwork365.vn',
    'autorandomvip.com',
    'trumsub.in',
    'shopphucvia.com',
    'uidclone.com',
    'shopbfviet.com',
    'rdbloxfruits.site',
    'adsfb.vin',
    'muarobuxvn.com',
    'mailsieungon.site',
    'storeroblox1s.com',
    'shoprobloxvip.com',
    'sieuthimail.online',
    'binhpc.com',
    'sieuthimail.vn',
    'nguyenlieuquangcao.com',
    'cuahangngon.com',
    'sieuthirobux.online',
    'rdtik.me',
    'thunkinrd.com',
    'chipbf.com',
    'clonevn.site',
    'phznszngrb.site',
    'cloudstorevn.site',
    'anhbastore.com',
    'shopaccgame24h.online',
    'nhuanphatshop.site',
    'acc5k.vn',
    'viprandom.site',
    'accbfgiare.site',
    'randombloxdn.com',
    'randomrbl247.com',
    'nqtam.dev',
    'pdshopbloxfruit.store',
    'boxrandom.online',
    'thanhbinhrdbf.shop',
    'chillstores.store',
    'shopphamthai.com',
    'shoproblox256.site',
    'clonemailco.site',
    'shopnnhrandom.com',
    'dichvusieungon.click',
    'trummailco.store',
    'xn--randomgir-71a7715f.vn',
    'xn--randomlinqun-zbb2i.vn',
    'xn--cahngrandom-96a0211h.vn',
    'xucauvang.vip',
    'clonetds.site',
    'bionemarket.shop',
    'randomvip1.com',
    'randomsieure.shop',
    'rdtuanpro.site',
    'sieurandom.com',
    'shopgauezb.site',
    'hailook.store',
    'sellaccvn.com',
    'bmvia.net',
    'myoglog.com',
    'fbclonetut.vn',
    'hienrom.com',
    'shopbanviagiare.com',
    'shopfb.io.vn',
    'shophuyga.com',
    'randomvip.me',
    'rdfb.online',
    'randomppg.com',
    'rdacccblox.com',
    'random.thanhhoi.store',
    'cuongroblox.store',
    'rdaccgiare.store',
    'mailclonevia.shop',
    'chienrd.online',
    'phntq.site',
    'random285.store',
    'tuandat888.xyz',
    'shopxure.com',
    'randomree.com',
    'randomaccgame.shop',
    'rdbuitiendat.com',
    'huprandom.com',
    'rdsieungon.com',
    'viafb247.com',
    'random15k.com',
    'shoprdtb.net',
    'via2h.com',
    'viausvn.com',
    'thegioiroblox.com',
    'shopclonevia.link',
    'shopgameso1.store',
    'mun88.me',
    'ntcheap.click',
    'xutraodoisub.com',
    'shopclone.fun',
    'muavia25.com',
    'rdtheblue.site',
    'hungrd.shop',
    'viabm.shop',
    'viaquangcao.com',
    'deepweb.vn',
    'shopclonenew76.fun',
    '456store.com',
    'robloxrenhat.com',
    'random24h.com',
    'shopadsfb24h.com',
    'haidangfb.com',
    'clonevns.site',
    'hasaki.io.vn'
];

 


if(in_array($_SERVER['HTTP_HOST'], $domain_black)) {
    echo 'Bạn đang vi phạm bản quyền của CMSNT.CO, vui lòng kích hoạt bản quyền trước khi dùng.<br><a href="https://www.cmsnt.co/">Mua giấy phép kích hoạt tại đây</a>';
}